name: Minimal JS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка проекта
        run: npm run build

      - name: Запуск тестов
        run: npm test

      - name: Publish (копируем файлы из dist в publish)
        run: |
          rm -rf publish
          mkdir publish
          cp -r dist/* publish/

      - name: Сохраняем артефакты (папку publish)
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: publish/
